ddW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('data.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [ # ! Order of the URLs is important !
    path('signup', views.sign_up, name="signup"),
    path('edit/<str:username>', views.edit_user, name="edit_user"),
    path('<str:username>', views.user_profile, name="user_profile"),

]

data/models.py
from django.db import models
from django.forms import ModelForm
from django.forms.widgets import TextInput
from users.models import Profile

# Create your models here.
# ! Defines data objects that the site will use !
# ! Like in the DatabaseNote.jpg attachment !

def get_default_user():
    try:
        return Profile.objects.get(user__username="Admin").id
    except Profile.DoesNotExist:
        return Profile.objects.all().first().id

class Fahrzeug(models.Model):
    name = models.CharField(max_length=100)
    farbe = models.CharField(max_length=8)
    baujahr = models.IntegerField()
    kaufdatum = models.DateField()
    preis = models.IntegerField()
    added_by = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, default=get_default_user)
    owners = models.ManyToManyField(Profile, related_name="fahrzeuge", through="FahrzeugServiceProfil")

    def __str__(self):
        return self.name

class Service(models.Model):
    was = models.TextField()
    wann = models.DateField()
    PRIOS = (
        ('Reparatur', 'Reparatur'),
        ('Service', 'Service'),
        ('TÜV', 'TÜV'),
        ('Pflege', 'Pflege'),
        ('Verbesserung', 'Verbesserung')
    )
    prio = models.CharField(
        max_length=14,
        choices=PRIOS
    )
    km = models.IntegerField()
    kostenpunkt = models.IntegerField()
    fahrzeug = models.ForeignKey(Fahrzeug, on_delete=models.SET_NULL, null=True)
    added_by = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, default=get_default_user)

    def __str__(self):
        return self.was + " am " + str(self.wann)


class FahrzeugServiceProfil(models.Model):
    fahrzeug = models.ForeignKey(Fahrzeug, related_name="user_mit_service", on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, related_name="fahrzeug_mit_service", on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True)


class FahrzeugServiceProfilForm(ModelForm):
    class Meta:
        model = FahrzeugServiceProfil
        fields = ('service',)


class FahrzeugAdd(ModelForm):
    class Meta:
        model = Fahrzeug
        fields = '__all__'
        exclude = ('added_by', 'owners',)
        widgets = {
            'farbe': TextInput(attrs={'type': 'color'}) # ! Color Picker !
        }

class ServiceAdd(ModelForm):
    class Meta:
        model = Service
        exclude = ('added_by',)
        fields = '__all__'

users/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_function = models.CharField(max_length=100, null=True, blank=True)

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('user_function', )
        labels = { # ! Dictionary for overwriting label of fields !
            "user_function": "Was arbeiten Sie, Womit kennen Sie sich aus?"
        }

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import Group, User
from data.views import home
from users.models import UserForm, ProfileForm, Profile
from data.models import FahrzeugServiceProfil, FahrzeugServiceProfilForm

# Create your views here.

def sign_up(request):
    if request.user.has_perm('auth.add_user'):
        if request.method =='POST':
            # ! Do something with form !
            form = UserCreationForm(request.POST)
            profile_form = ProfileForm(request.POST)

            if form.is_valid():
                form.save()
                new_user = form.save()
                group = Group.objects.get(name="Normal")
                new_user.groups.add(group)
                new_user.save()
                profile = profile_form.save(commit=False)
                profile.user = new_user
                profile.save()
                if (new_user):
                    login(request, new_user)
                return redirect(home)
        else:
            form = UserCreationForm()
            profile_form = ProfileForm()
    else:
        return redirect(home)

    context = {
    'form': form,
    'profile_form':profile_form,
    }

    return render(request, "signup.html", context)


def user_profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect(home)

    return render(request, "user_profile.html", {'user_object': user})


def edit_user(request, username):
    profile = None
    try:
        user = User.objects.get(username=username)
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            pass # ! Just go ahead !
    except User.DoesNotExist:
        return redirect(home)

    if request.user.has_perm('auth.change_user') or request.user.username == username:
        if request.method == 'POST':
            form = UserForm(request.POST, instance=user)

            if profile:
                profile_form = ProfileForm(request.POST, instance = profile)
            else:
                profile_form = ProfileForm(request.POST)

            if form.is_valid():
                updated_user = form.save()
                if profile_form.is_valid():
                    new_profile = profile_form.save(commit=False)
                    new_profile.user = updated_user
                    new_profile.save()

                return redirect(user_profile, username=username)
        else:
            form = UserForm(instance=user)
            if profile:
                profile_form = ProfileForm(instance=profile)
            else:
                profile_form = ProfileForm()

        context = {'form': form,
                    'username': username,
                    'profile_form': profile_form,
        }

        return render(request, "edit_user.html", context)

    return redirect(home)

users/templates/edit_user.html
{% extends 'index.html' %}
{% block content %}

</br></br>
{% if perms.users.change_user or user.username == username %}
<h3>Account "{{ username }}" bearbeiten</h3></br>
<form method="post" actions="{% url 'edit_user' username=username %}">
{% csrf_token %}
{{form}}
{{profile_form}}
</br></br><input type="submit" value="Speichern" />
{% endif %}

{% endblock %}

users/templates/signup.html
{% extends 'index.html' %}
{% block content %}

</br></br>
<h3>Registrieren</h3></br>
<form method="post" actions="{% url 'signup' %}">
{% csrf_token %}
{{form}}
</br> 
{{profile_form}}
</br></br><input type="submit" value="registrieren" />


{% endblock %}

users/templates/user_profile.html
{% extends 'index.html' %}
{% block content %}
{% load static %}

</br></br>
{% if perms.users.view_profile or user.username == user_object.username %}
<h3>Account "{{user_object.username}}"</h3></br>

<p>{{user_object.first_name}} {{user_object.last_name}}</p>
<p>{{user_object.profile.user_function}}</p>
<p>Registriert am {{user_object.date_joined|date:'d. F Y'}}</p></br>

{% if perms.users.change_profile or user.username == user_object.username %}
<a class="button" href="{% url 'edit_user' user_object.username %}">Ändern</a>
{% endif %}
{% endif %}

</br></br></br>

<h5>Betreute Fahrzeuge</h5>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Farbe</th>
      <th>Baujahr</th>
      <th>Kaufdatum</th>
      <th>Kaufpreis</th>
      <th>Hinzugefügt von</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for fahrzeug in user_object.profile.fahrzeuge.all %}
      <tr>
      <td>
        {% if perms.users.change_profile or user.username == user_object.username %}
          <a href="{% url 'uncollect_fahrzeug' fahrzeug.id %}">
              <img src="{% static 'images/delete.png' %}" />
        {% endif %}
      </td>
      <td> <a href={% url 'home' fahrzeug_name=fahrzeug.id %}>{{fahrzeug.name}}</a></td>
      <td style="background:{{fahrzeug.farbe}}"></td>
      <td> {{fahrzeug.baujahr}}</td>
      <td> {{fahrzeug.kaufdatum}}</td>
      <td> {{fahrzeug.preis}} €</td>
      <td> <a href="{% url 'user_profile' fahrzeug.added_by.user.username %}">{{fahrzeug.added_by.user.username}}</a></td>
      <td>
        {% if perms.data.change_fahrzeug %}
        <a href="{% url 'FahrzeugEdit' fahrzeug.id %}">Ändern</a></td>
        {% endif %}
      <td>
        {% if perms.data.delete_fahrzeug %}
        <a href="{% url 'FahrzeugDelete' fahrzeug.id %}">Löschen</a></td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}