data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about', views.about, name="about"),
    path('info', views.info, name="info"),
    path('addcar', views.edit_Fahrzeug, name="FahrzeugAdd"),
    path('addserv', views.edit_Service, name="ServiceAdd"),
    path('editcar/<int:fahrzeug_id>', views.edit_Fahrzeug, name="FahrzeugEdit"),
    path('editcar/delete/<int:fahrzeug_id>', views.delete_Fahrzeug, name="FahrzeugDelete"),
    path('editservice/<int:service_id>', views.edit_Service, name="ServiceEdit"),
    path('editservice/delete/<int:service_id>', views.delete_Service, name="ServiceDelete"),
    path('collect_fahrzeug/<int:fahrzeug_id>', views.collect_fahrzeug, name="collect_fahrzeug"),
    path('uncollect_fahrzeug/<int:fahrzeug_id>', views.uncollect_fahrzeug, name="uncollect_fahrzeug"),
    path('suche-<str:fahrzeug_name>', views.home, name="home")
]

ddW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('data.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
]

data/models.py
from django.db import models
from django.forms import ModelForm
from django.forms.widgets import TextInput
from users.models import Profile

# Create your models here.
# ! Defines data objects that the site will use !
# ! Like in the DatabaseNote.jpg attachment !

def get_default_user():
    try:
        return Profile.objects.get(user__username="Admin").id
    except Profile.DoesNotExist:
        return Profile.objects.all().first().id

class Fahrzeug(models.Model):
    name = models.CharField(max_length=100)
    farbe = models.CharField(max_length=8)
    baujahr = models.IntegerField()
    kaufdatum = models.DateField()
    preis = models.IntegerField()
    added_by = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, default=get_default_user)
    owners = models.ManyToManyField(Profile, related_name="fahrzeuge", through="FahrzeugServiceProfil")

    def __str__(self):
        return self.name

class Service(models.Model):
    was = models.TextField()
    wann = models.DateField()
    PRIOS = (
        ('Reparatur', 'Reparatur'),
        ('Service', 'Service'),
        ('TÜV', 'TÜV'),
        ('Pflege', 'Pflege'),
        ('Verbesserung', 'Verbesserung')
    )
    prio = models.CharField(
        max_length=14,
        choices=PRIOS
    )
    km = models.IntegerField()
    kostenpunkt = models.IntegerField()
    fahrzeug = models.ForeignKey(Fahrzeug, on_delete=models.SET_NULL, null=True)
    added_by = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, default=get_default_user)

    def __str__(self):
        return self.was + " am " + str(self.wann)


class FahrzeugServiceProfil(models.Model):
    fahrzeug = models.ForeignKey(Fahrzeug, related_name="user_mit_service", on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, related_name="fahrzeug_mit_service", on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True)


class FahrzeugServiceProfilForm(ModelForm):
    class Meta:
        model = FahrzeugServiceProfil
        fields = ('service',)


class FahrzeugAdd(ModelForm):
    class Meta:
        model = Fahrzeug
        fields = '__all__'
        exclude = ('added_by', 'owners',)
        widgets = {
            'farbe': TextInput(attrs={'type': 'color'}) # ! Color Picker !
        }

class ServiceAdd(ModelForm):
    class Meta:
        model = Service
        exclude = ('added_by',)
        fields = '__all__'

data/views.py
from django.shortcuts import render, redirect
from data.models import Fahrzeug, Service, FahrzeugAdd, ServiceAdd, FahrzeugServiceProfil

# Create your views here.
# ! This is where to provide the information for the web pages to display !
# ! Process things, query the database, make calculations !

def home(request, fahrzeug_name=None):

    fahrzeuge = Fahrzeug.objects.all()
    fahrzeug_header = Fahrzeug.objects.filter(id=fahrzeug_name)

    if fahrzeug_name is not None:
        services = Service.objects.filter(fahrzeug=fahrzeug_name)
    else:
        services = Service.objects.all() # ! Query the Database for all Services !

    if (request.user.is_authenticated):
        fahrzeug_ids = request.user.profile.fahrzeuge.values_list('id', flat=True)
    else:
        fahrzeug_ids = None

    context = { # ! {} is a dictionary, can hold any type of value. !
        'service_list': services,
        'fahrzeug_ids': fahrzeug_ids,
        'fahrzeug_list': fahrzeuge,
        'fahrzeug_name': fahrzeug_name,
        'fahrzeug_header': fahrzeug_header,
    }

    return render(request, "home.html", context)


def edit_Fahrzeug(request, fahrzeug_id=None):

    if request.method == 'POST':

        if fahrzeug_id is not None:
            fahrzeug = Fahrzeug.objects.get(id=fahrzeug_id)
            form = FahrzeugAdd(request.POST, instance=fahrzeug)
        else:
            form = FahrzeugAdd(request.POST)

        if form.is_valid():
            updated_fahrzeug = form.save(commit=False)
            updated_fahrzeug.added_by = request.user.profile
            updated_fahrzeug.save()
            return redirect(home)

    else:
        if fahrzeug_id is not None:
            fahrzeug = Fahrzeug.objects.get(id=fahrzeug_id)
            form = FahrzeugAdd(instance=fahrzeug)
        else:
            form = FahrzeugAdd()

    return render(request, "edit.html", {'form': form, 'fahrzeug_id': fahrzeug_id})


def delete_Fahrzeug(request, fahrzeug_id):
    fahrzeug = Fahrzeug.objects.get(id=fahrzeug_id)
    fahrzeug.delete()

    return redirect(home)


def edit_Service(request, service_id=None):

    if request.method == 'POST':

        if service_id is not None:
            service = Service.objects.get(id=service_id)
            form = ServiceAdd(request.POST, instance=service)
        else:
            form = ServiceAdd(request.POST)

        if form.is_valid():
            updated_service = form.save(commit=False)
            updated_service.added_by = request.user.profile
            updated_service.save()
            return redirect(home)

    else:
        if service_id is not None:
            service = Service.objects.get(id=service_id)
            form = ServiceAdd(instance=service)
        else:
            form = ServiceAdd()

    return render(request, "edit.html", {'form': form, 'service_id': service_id})


def delete_Service(request, service_id):
    service = Service.objects.get(id=service_id)
    service.delete()

    return redirect(home)


def collect_fahrzeug(request, fahrzeug_id):
    try:
        fahrzeug = Fahrzeug.objects.get(id=fahrzeug_id)
    except Fahrzeug.DoesNotExist:
        return redirect(home)

    if (not request.user.is_authenticated):
        return redirect(home)

    FahrzeugServiceProfil(fahrzeug=fahrzeug, profile=request.user.profile, service=None).save()
    return redirect(home)


def uncollect_fahrzeug(request, fahrzeug_id):
    try:
        fahrzeug = Fahrzeug.objects.get(id=fahrzeug_id)
    except Fahrzeug.DoesNotExist:
        return redirect('user_profile', request.user.username)

    if (not request.user.is_authenticated):
        return redirect(home)

    fahrzeug.owners.remove(request.user.profile)
    fahrzeug.save()
    return redirect('user_profile', request.user.username)


def info(request):

    return render(request, 'info.html', {})


def about(request):

    return render(request, 'about.html', {})    # ! Ausgabe des Impressum --> templates !

data/templates/about.html
{% extends 'index.html' %}

{% block content %}

</br></br><h4>Impressum</h4>
<div class="entry-content">

    Haftung für Inhalte:

    Als Anbieter bin ich gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG bin ich als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden diese Inhalte umgehend entfernt.

    <br/><br/>Haftung für Links:

    Auf eventuell enthaltene Links zu externen Webseiten Dritter, habe ich keinen inhaltlichen Einfluss. Deshalb kann ich für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden derartige Links umgehend entfernt.

    <br/><br/>Urheberrecht:

    Die durch mich erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung von mir. Downloads und Kopien dieser Seite sind nicht gestattet, außer ausdrücklich erlaubt. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden derartige Inhalte umgehend entfernt.
    <br/>
    <br/>Besitzer: <a href="http://zechs.de" target="_blank" rel="noopener noreferrer">Paul Zech, Lohebergweg 6a, 83093 Bad Endorf</a>
    <br/>
    <br/>Quellcode <a href="https://github.com/Baule8520/ddw" target="_blank" rel="noopener noreferrer">auf Github</a>
    <br/>
    <br/>Tutorial <a href="https://skl.sh/2Z63gjG" target="_blank" rel="noopener noreferrer">auf Skillshare</a>
    </div><br/><br/>

{% endblock %}

data/templates/edit.html
{% extends 'index.html' %}

{% block content %}

</br><h4>{% if fahrzeug_id %}Editieren eines Fahrzeugs:{% elif service_id %}Editieren eines Service:{% else %}Hinzufügen{% endif %}</h4>

<form action="" method="post">
{% csrf_token %}
{{form}}
</br>
<input class="button" type="submit">
</form>

{% endblock %}

data/templates/home.html
{% extends 'index.html' %}

{% block content %}

{% load static %}

  <div class="row">
    <p>
    {% if user.is_authenticated %}
      <h5>Hallo, {{user.username}}!</h5>
      <a class="button" href={% url 'user_profile' user.username %}> Zum Profil</a>
      <a class="button" href="{% url 'logout' %}">Logout?</a>
    {% else %}
      <a class="button" href="{% url 'login' %}">Zum Login</a>
    {% endif %}
    </p>
  </div>

  {% if perms.data.view_fahrzeug %}
  <div class="row">
  {% if fahrzeug_name %}
  {% for header in fahrzeug_header %}
  <h5>Alle Services von <b>{{header.name}}</b>:</h5>
  {% endfor %}
  {% else %}
      <h5>Alle Fahrzeuge</h5>
      <p>Anzahl der Fahrzeuge: {{fahrzeug_list|length}}</p>
      <table>
        <thead>
          <tr>
            <th>Betreut?</th>
            <th>Name</th>
            <th>Farbe</th>
            <th>Baujahr</th>
            <th>Kaufdatum</th>
            <th>Kaufpreis</th>
            <th>Hinzugefügt von</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for fahrzeug in fahrzeug_list %}
            <tr>
            <td>{% if fahrzeug.id in fahrzeug_ids %}
                  <img src="{% static 'images/check.png' %}" />
                {% else %}
              <a href="{% url 'collect_fahrzeug' fahrzeug.id %}">
                  <img src="{% static 'images/save.png' %}" /></a>
                {% endif %}
            </td>
            <td> <a href={% url 'home' fahrzeug_name=fahrzeug.id %}>{{fahrzeug.name}}</a></td>
            <td style="background:{{fahrzeug.farbe}}"></td>
            <td> {{fahrzeug.baujahr}}</td>
            <td> {{fahrzeug.kaufdatum}}</td>
            <td> {{fahrzeug.preis}} €</td>
            <td> <a href="{% url 'user_profile' fahrzeug.added_by.user.username %}">{{fahrzeug.added_by.user.username}}</a></td>
            <td>
              {% if perms.data.change_fahrzeug %}
              <a href="{% url 'FahrzeugEdit' fahrzeug.id %}">Ändern</a></td>
              {% endif %}
            <td>
              {% if perms.data.delete_fahrzeug %}
              <a href="{% url 'FahrzeugDelete' fahrzeug.id %}">Löschen</a></td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if perms.data.add_fahrzeug %}
      <a class="button" href="{% url 'FahrzeugAdd' %}">Hinzufügen</a>
      {% endif %}
    </div>
    {% endif %}
    {% endif %}

    {% if perms.data.view_service %}
    {% if not fahrzeug_name %}
    <div class="row"> </br></br>
      <h5>Alle Serviceleistungen</h5>
    {% endif %}
      <p>Anzahl der Serviceleistungen: {{service_list|length}}</p>
      <table>
        <thead>
          <tr>
            <th>Was</th>
            <th>Wann</th>
            <th>Art der Leistung</th>
            <th>Bei Kilometer</th>
            <th>Kosten</th>
            <th>Fahrzeug</th>
            <th>Ausführende Person</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for service in service_list %}
          <tr>
          <td> {{service.was}}</td>
          <td> {{service.wann}}</td>
          <td> {{service.prio}}</td>
          <td> {{service.km}}</td>
          <td> {{service.kostenpunkt}} €</td>
          <td> {{service.fahrzeug}}</td>
          <td> <a href="{% url 'user_profile' service.added_by.user.username %}">{{service.added_by.user.username}}</a></td>
          <td>
            {% if perms.data.change_service %}
            <a href="{% url 'ServiceEdit' service.id %}">Ändern</a></td>
            {% endif %}
          <td>
            {% if perms.data.delete_service %}
            <a href="{% url 'ServiceDelete' service.id %}">Löschen</a></td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if perms.data.add_service %}
      {% if fahrzeug_name %}
        <a class="button" href="{% url 'home' %}"><-- Zurück</a>
      {% endif %}
      <a class="button" href="{% url 'ServiceAdd' %}">Hinzufügen</a>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}

data/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>FSD</title>
  <meta name="description" content="Data Driven Website">
  <meta name="author" content="Paul Z.">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS last one loaded will overwrite the others...!
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">

</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
<div class="container">

</br><h2>Fahrzeug Service Datenbank</h2>
</br>
<a class="button" href="{% url 'home' %}">Home</a>
<a class="button" href="{% url 'info' %}">Informationen</a>
<a class="button" href="{% url 'about' %}">Impressum</a>
<a class="button" href="{% url 'admin:index' %}">Zum Admin Bereich</a>
{% block content %}

{% endblock %}
</div>
<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

data/templates/info.html
{% extends 'index.html' %}

{% block content %}

</br></br><h4>Informationen zur Nutzung der Fahrzeug Service Datenbank</h4>
<div class="entry-content">

Noch zu Ergänzen...

</div><br/><br/>

{% endblock %}